"""Make visible_columns non-nullable with default []

Revision ID: 001cb025f461
Revises: c9cb216e75dc
Create Date: 2025-07-16 14:31:24.610629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001cb025f461'
down_revision: Union[str, None] = 'c9cb216e75dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) Añade la columna como INTEGER[] no nullable con default vacío
    op.add_column(
        "users",
        sa.Column(
            "hidden_columns",
            postgresql.ARRAY(sa.Integer()),
            nullable=False,
            server_default=sa.text("'{}'::integer[]"),
        ),
    )
    # 2) (Opcional) Si ya hay usuarios y en algún caso el valor puede quedar NULL,
    #    normalízalos ahora:
    op.execute(
        "UPDATE users SET hidden_columns = '{}' WHERE hidden_columns IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visible_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'hidden_columns')
    # ### end Alembic commands ###
