"""Se agrega un JSOB a USER para guardar las columnas ocultas

Revision ID: 1857fb618633
Revises: 2b8ce73432e1
Create Date: 2025-07-16 14:14:13.148346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1857fb618633'
down_revision: Union[str, None] = '2b8ce73432e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visible_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visible_columns')
    # ### end Alembic commands ###
