"""Make hidden_columns int to strings

Revision ID: 6ba2fc716fb8
Revises: 001cb025f461
Create Date: 2025-07-16 15:14:23.059893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba2fc716fb8'
down_revision: Union[str, None] = '001cb025f461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ALTER TABLE users ALTER COLUMN hidden_columns TYPE text[]
    op.alter_column(
        "users",
        "hidden_columns",
        type_=postgresql.ARRAY(sa.Text()),
        postgresql_using="hidden_columns::text[]",
        nullable=False,
        server_default=sa.text("ARRAY[]::text[]")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visible_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
