"""Se crea tabla de users

Revision ID: 83b61e278acc
Revises: 81b82bd2aa65
Create Date: 2025-07-09 12:46:04.086849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b61e278acc'
down_revision: Union[str, None] = '81b82bd2aa65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actividad_enzimatica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecitinasa', sa.String(), nullable=True),
    sa.Column('ureasa', sa.String(), nullable=True),
    sa.Column('lipasa', sa.String(), nullable=True),
    sa.Column('amilasa', sa.String(), nullable=True),
    sa.Column('proteasa', sa.String(), nullable=True),
    sa.Column('catalasa', sa.String(), nullable=True),
    sa.Column('celulasa', sa.String(), nullable=True),
    sa.Column('fosfatasa', sa.String(), nullable=True),
    sa.Column('aia', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envio_puq', sa.String(), nullable=True),
    sa.Column('temperatura_menos80', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caracterizacion_genetica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gen_16s', sa.String(), nullable=True),
    sa.Column('metabolomica', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crecimiento_temperatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_5', sa.String(), nullable=True),
    sa.Column('temp_25', sa.String(), nullable=True),
    sa.Column('temp_37', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medios_cultivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medio', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morfologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gram', sa.String(), nullable=True),
    sa.Column('morfologia_1', sa.String(), nullable=True),
    sa.Column('morfologia_2', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.Column('nombre_proyecto', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resistencia_antibiotica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amp', sa.String(), nullable=True),
    sa.Column('ctx', sa.String(), nullable=True),
    sa.Column('cxm', sa.String(), nullable=True),
    sa.Column('caz', sa.String(), nullable=True),
    sa.Column('ak', sa.String(), nullable=True),
    sa.Column('c', sa.String(), nullable=True),
    sa.Column('te', sa.String(), nullable=True),
    sa.Column('am_ecoli', sa.String(), nullable=True),
    sa.Column('am_saureus', sa.String(), nullable=True),
    sa.Column('cepa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cepa_id'], ['cepas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cepas', sa.Column('cod_lab', sa.String(), nullable=True))
    op.add_column('cepas', sa.Column('pigmentacion', sa.String(), nullable=True))
    op.add_column('cepas', sa.Column('origen', sa.String(), nullable=True))
    op.add_column('cepas', sa.Column('datos_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_cepas_id', table_name='cepas')
    op.drop_column('cepas', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cepas', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_cepas_id', 'cepas', ['id'], unique=False)
    op.drop_column('cepas', 'datos_extra')
    op.drop_column('cepas', 'origen')
    op.drop_column('cepas', 'pigmentacion')
    op.drop_column('cepas', 'cod_lab')
    op.drop_table('resistencia_antibiotica')
    op.drop_table('proyectos')
    op.drop_table('morfologia')
    op.drop_table('medios_cultivo')
    op.drop_table('crecimiento_temperatura')
    op.drop_table('caracterizacion_genetica')
    op.drop_table('almacenamiento')
    op.drop_table('actividad_enzimatica')
    op.drop_table('users')
    # ### end Alembic commands ###
